# Generated by Django 4.1.1 on 2022-11-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
    ]
